# Generated by Django 5.0.6 on 2024-07-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0009_alter_profile_profileimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user2',
        ),
    ]
