# Generated by Django 5.0.6 on 2024-07-08 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0010_rename_user_profile_user2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user2',
            new_name='user',
        ),
    ]
