# Generated by Django 5.0.6 on 2024-07-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0011_rename_user2_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank-profile.png', upload_to='profile_images'),
        ),
    ]
