# Generated by Django 5.0.6 on 2024-07-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0012_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank_profile.png', upload_to='profile_images'),
        ),
    ]
