# Generated by Django 5.0.6 on 2024-07-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0018_sample_sample2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample2',
            name='auth',
        ),
        migrations.DeleteModel(
            name='sample',
        ),
        migrations.DeleteModel(
            name='sample2',
        ),
    ]
